// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfA-xyljEBi7S8JPvW3qd0wKXBrcbMMBU',
    appId: '1:435003677712:web:ce9d4ea4cfc18a32ea7e95',
    messagingSenderId: '435003677712',
    projectId: 'ecojp-8b952',
    authDomain: 'ecojp-8b952.firebaseapp.com',
    storageBucket: 'ecojp-8b952.firebasestorage.app',
    measurementId: 'G-8ZTY1GPL52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvB1c_hGi_rR6qfB7UeDFJ_MtmGppcms8',
    appId: '1:435003677712:android:f6280af24b70fd7fea7e95',
    messagingSenderId: '435003677712',
    projectId: 'ecojp-8b952',
    storageBucket: 'ecojp-8b952.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLywqZ5kWdwDf1Fq9CdaxxCZpP_W2nO8U',
    appId: '1:435003677712:ios:12ee28028ab9726dea7e95',
    messagingSenderId: '435003677712',
    projectId: 'ecojp-8b952',
    storageBucket: 'ecojp-8b952.firebasestorage.app',
    iosBundleId: 'com.example.ecoJp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLywqZ5kWdwDf1Fq9CdaxxCZpP_W2nO8U',
    appId: '1:435003677712:ios:12ee28028ab9726dea7e95',
    messagingSenderId: '435003677712',
    projectId: 'ecojp-8b952',
    storageBucket: 'ecojp-8b952.firebasestorage.app',
    iosBundleId: 'com.example.ecoJp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfA-xyljEBi7S8JPvW3qd0wKXBrcbMMBU',
    appId: '1:435003677712:web:28ea4f8ef1b229d2ea7e95',
    messagingSenderId: '435003677712',
    projectId: 'ecojp-8b952',
    authDomain: 'ecojp-8b952.firebaseapp.com',
    storageBucket: 'ecojp-8b952.firebasestorage.app',
    measurementId: 'G-300SL32CDL',
  );
}
